spring:
  profiles:
    active: local

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: PostgresHikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 1000

  cloud:
    gcp:
      storage:
        bucket: ${GCS_BUCKET_NAME:union-app-miniapps}

jwt:
  secret: ${JWT_SECRET:union-super-app-jwt-secret-key-must-be-at-least-256-bits-long-for-hs256}
  access-token-expiration: 1800000     # 30분
  refresh-token-expiration: 1209600000  # 14일

careernet:
  api:
    key: ${CAREERNET_API_KEY}

cdn:
  base-url: ${CDN_BASE_URL}
  key-name: ${CDN_KEY_NAME}
  key-value: ${CDN_KEY_VALUE}
